### ISSUE TITLE
Macros containing compound conditionals need to be surrounded by parentheses

### ISSUE THREAD

**Issue by gth828r** [ChrisRx/quickavro#16]
I was testing reading in some files using quickavro and serializing them to byte buffers, and I found that I was getting unexpected validation errors when running under python2 at this line:
https://github.com/ChrisRx/quickavro/blob/master/src/convert.c#L378

It looks like the issue is that the function being called is a macro implementing a compound conditional with an or statement in it:
https://github.com/ChrisRx/quickavro/blob/master/src/compat.h#L49

The problem is that the negation of this macro is not applied to both parts of the boolean statement.  The compound conditional macros should be defined with parentheses around them.

**Comment by gth828r** [comment]
I just wanted to check in on this.  No rush at this time, but I wanted to make sure it doesn't slip through the cracks since I submitted it over the week of a US holiday.

**Comment by ChrisRx** [comment]
Sorry for the delay, I merged it and will be updating PyPi

**Comment by gth828r** [comment]
No problem, thanks!
