### ISSUE TITLE
Fixes for #19 not in latest pypi release

### ISSUE THREAD

**Issue by gth828r** [ChrisRx/quickavro#22]
It appears that the fixes to #19 did not make it into the latest pypi release (0.1.19).  I found some failures in my tests when using the latest from pypi that were not present when building master from a github clone.  When I grabbed the source tarball from https://pypi.python.org/pypi/quickavro, I noticed that the changes in https://github.com/ChrisRx/quickavro/commit/2ed84315c5ff060e960686ab9dee175866d89919 were not present in `convert.c`.  Can you double check this, and cut a new release from the current master if indeed those fixes are not in the latest pypi release?  Thanks!

**Comment by ChrisRx** [comment]
I thought I had pushed it but clearly was mistaken.  I will be able to push the latest release this evening.  Because of how PyPi works, I'm going to increment the version again to 0.1.20 to make sure it doesn't do something weird.

**Comment by gth828r** [comment]
No problem, I will watch for the new version.  Thanks!

**Comment by ChrisRx** [comment]
I think that fixed it.  Let me know if it doesn't.

**Comment by gth828r** [comment]
I ran some tests with the new release, and things look ok now.  Closing this issue out!
