### ISSUE TITLE
support for optional attributes

### ISSUE THREAD

**Issue by yan-hic** [ChrisRx/quickavro#24]
This is not explicit in the documentation: does quickavro support **doc** and **aliases** attributes at record and field-level ?

**Comment by ChrisRx** [comment]
If it is supported by AvroC, it _should_ be supported, since the record and fields are handed off to the AvroC API.  Have you tried it and found something not to be working with those record and field-level attributes?

**Comment by ChrisRx** [comment]
Closing due to lack of response.  Please reopen if you want to continue working through this issue!
