### ISSUE TITLE
New release coming?

### ISSUE THREAD

**Issue by gth828r** [ChrisRx/quickavro#29]
I was wondering if you could cut a new PyPI release soon.  There were a couple of fixes that you picked up back in February (thanks for that!) which are now in master, but they have not made it into a new PyPI release.  I am able to track the latest with those fixes in my packaging by pulling from Github, but it would be good to get an official release through PyPI.

**Comment by ChrisRx** [comment]
For some reason I thought I had already, but clearly goofed.  I uploaded a new version 0.1.22, let me know if that doesn't work or I missed anything.

**Comment by ChrisRx** [comment]
I think I see what happened.  I neglected to increment the version after merging your PRs so when I came back later to check the PyPI version to make sure it was up-to-date and the version in the repo matched, despite there having been changes.  I'll try to be more aware of this in the future to prevent it from happening again.  Thanks for following up!

**Comment by gth828r** [comment]
No problem, we weren't ready in my project's schedule to incorporate a new release until now anyway.  Thanks for quickly resolving this!
